version: "3.9"
services:

  engine:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: engine
    volumes:
    - ./mounts/data:/usr/src/app/data
    depends_on:
      - nats-server

  handler:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: handler
    ports:
      - "8080:8080"
    depends_on:
      - engine
      - nats-server

  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    logging:
      driver: none # disable logging

  build_proto:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: development
    # ports:
    #   - "8080:80"
    volumes:
      - ./mounts/proto:/usr/src/app/generated_proto
      # - ./mounts/data:/usr/src/app/data
    # depends_on:
    #   - nats-server