version: "3.9"
services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    # ports:
    #   - "80:3000"

  engine:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: engine
    environment:
      # HABITS_CONFIG_FILE: config/engine.toml
      HABITS_NATS.CONNECTION_STRING: nats://nats-server:4222
    volumes:
    - ./backend/config/engine.toml:/app/config.toml
    - ./mounts/data:/app/data
    depends_on:
      - nats-server

  handler:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: handler
    ports:
      - "8080:8080"
    environment:
      # HABITS_CONFIG_FILE: config/handler.toml
      HABITS_NATS.CONNECTION_STRING: nats://nats-server:4222
    volumes:
      - ./backend/config/handler.toml:/app/config.toml
    depends_on:
      - engine
      - nats-server

  nats-server:
    image: nats
    # ports:
    #   - "4222:4222"
    #   - "8222:8222"
    logging:
      driver: none # disable logging

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      FRONTEND_HOST: host.docker.internal
      FRONTEND_PORT: 3000
      HANDLER_HOST: handler
      HANDLER_PORT: 8080