version: "3.9"
services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:3000"

  engine:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: engine
    environment:
      HABITS_NATS.CONNECTION_STRING: nats://nats-server:4222
    volumes:
    - ./mounts/data:/app/data
    - ./backend/config:/app/config
    depends_on:
      - nats-server

  handler:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        EXEC_APP_NAME: handler
    ports:
      - "8080:8080"
    volumes:
      - ./backend/config:/app/config
    depends_on:
      - engine
      - nats-server

  nats-server:
    image: nats
    # ports:
    #   - "4222:4222"
    #   - "8222:8222"
    logging:
      driver: none # disable logging